[workspace]
authors = ["FreekPols <c.f.j.pols@tudelft.nl>"]
channels = ["conda-forge"]
name = "manual"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
teachbooks = "teachbooks build book"
server = "teachbooks serve"
editor = "jupyter lab"
teachbooks_install = "pixi import --format=pypi-txt --environment=default requirements.txt"

[dependencies]
python = ">=3.14.7,<3.15"
jupyterlab = ">=4.6.3,<5"

[pypi-dependencies]
jupyterlab-myst = ">=2.7.0, <3"
